const EASY_WORDS = [
    "apple",
    "banana",
    "pizza",
    "burger",
    "ice cream",
    "cake",
    "donut",
    "carrot",
    "mushroom",
    "coffee",
    "bottle",
    "cup",
    "chair",
    "table",
    "bed",
    "lamp",
    "clock",
    "key",
    "lock",
    "house",
    "tree",
    "flower",
    "mountain",
    "cloud",
    "sun",
    "moon",
    "star",
    "rainbow",
    "fire",
    "snowman",
    "bicycle",
    "car",
    "bus",
    "train",
    "airplane",
    "boat",
    "rocket",
    "guitar",
    "piano",
    "drum",
    "camera",
    "phone",
    "computer",
    "television",
    "book",
    "pencil",
    "backpack",
    "hat",
    "shoe",
    "umbrella",
];

const MEDIUM_WORDS = [
    "volcano",
    "lighthouse",
    "submarine",
    "windmill",
    "waterfall",
    "bridge",
    "skyscraper",
    "roller coaster",
    "ferris wheel",
    "pirate ship",
    "treasure chest",
    "haunted house",
    "campfire",
    "aquarium",
    "zoo",
    "hospital",
    "school",
    "airport",
    "supermarket",
    "restaurant",
    "library",
    "museum",
    "prison",
    "laboratory",
    "spaceship",
    "satellite",
    "telescope",
    "robot",
    "dinosaur",
    "dragon",
    "unicorn",
    "alien",
    "vampire",
    "zombie",
    "skeleton",
    "ghost",
    "astronaut",
    "firefighter",
    "detective",
    "pirate",
    "cowboy",
    "magician",
    "king",
    "queen",
    "knight",
    "farmer",
    "chef",
    "scientist",
    "doctor",
    "photographer",
];

const HARD_WORDS = [
    "time machine",
    "black hole",
    "solar eclipse",
    "meteor shower",
    "ancient temple",
    "secret laboratory",
    "abandoned mansion",
    "underwater city",
    "alien invasion",
    "dinosaur fossil",
    "haunted forest",
    "monster under the bed",
    "escape room",
    "zombie apocalypse",
    "space station",
    "medieval battlefield",
    "pirate treasure",
    "forbidden door",
    "magic portal",
    "cursed book",
    "invisible man",
    "mad scientist",
    "giant robot",
    "shrinking machine",
    "flying car",
    "underwater volcano",
    "lost civilization",
    "parallel universe",
    "wormhole",
    "apocalypse bunker",
    "mysterious island",
    "secret passage",
    "ancient artifact",
    "crystal cave",
    "enchanted forest",
    "floating island",
    "alien abduction",
    "bank robbery",
    "crime scene",
    "prison escape",
    "train robbery",
    "monster attack",
    "wizard duel",
    "pirate battle",
    "medieval siege",
    "space battle",
    "dinosaur attack",
    "superhero battle",
    "underwater treasure",
];

export const WORDS = [...EASY_WORDS, ...MEDIUM_WORDS, ...HARD_WORDS];
